# SonarQube project settings
sonar.projectKey=review-service
sonar.projectName=Review Service
sonar.sources=src,review.handler.js,grpc_server.js,server.js,start.js
sonar.exclusions=**/app/generated/**,**/node_modules/**,**/k8s/**,**/.git/**,**/protos/**
sonar.javascript.exclusions=**/app/generated/**
sonar.test.inclusions=**/*test*.js
