apiVersion: v1
kind: Secret
metadata:
  name: review-service-secret
  namespace: review-service
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://sash1ru:Ob2MfAHqig8x1XXt@restbackend.vfbr0.mongodb.net/?appName=RESTBackend