apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: review-service
  labels:
    app: review-service
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
    - name: rest
      port: 8002
      targetPort: rest
      protocol: TCP
    - name: grpc
      port: 50052
      targetPort: grpc
      protocol: TCP